#!/bin/bash

# Update conda to the latest version (optional)
conda update -n base -c conda-forge conda -y || echo "Could not update conda. Continuing with build."

# Install Julia packages (without IJulia)
julia -e 'using Pkg; 
           Pkg.activate("."); 
           Pkg.add("Distributions"); 
           Pkg.add("Turing"); 
           Pkg.add("StatsPlots");  # Add any other packages you need
           Pkg.instantiate(); 
           Pkg.resolve()'  # Resolve and update the manifest
