[package]
name = "Turing"
uuid = "1c2b4b39-ab0a-4f59-bb42-4948fb304887"
version = "0.1.0"

[deps]
Turing = "fce5fe82-1a69-5db0-8435-530cda43e40d"      # For probabilistic programming
StatsPlots = "f3b207a7-9fa1-5c79-82b3-8d84c6a27b59" # For statistical plotting
